apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::330063562316:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-eMZSv8tBX0x5
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::330063562316:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-25T23:52:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1438"
  uid: 860ac0a6-307c-4608-9dbd-c96386cc85b2
